#! /usr/bin/bash
# arguments: job_id job_dir ldms_slurmenv
# setup env for ldmsd and run for user
# job_id: slurm job id
# job_dir: pwd where the job is launched, or user customizable dump for all ldms bits
# ldms_slurmenv: environment file for ldmsd -- generated by default; may be overridden
#                if another file following the same variable conventions is wanted.
# Requires:
# a) ldmsd installed from source
# b) the arguments above
# c) user willing to run without an aggregator
#
# Affected by environment variables:
# LDMS_PREFIX (set this in your shell environment, or Ben's at Sandia is assumed).

# this line must be adjusted to point at your ldms installation
# if you don't set LDMS_PREFIX in your shell
export LDMS_PREFIX=/usr/projects/workflow_perf/ovis/install
if test -z "$LDMS_PREFIX"; then
	ldms_prefix=/ascldap/users/baallan/chama/OVIS-3.4.4/LDMS_install
fi
export ldms_prefix=$LDMS_PREFIX
MYhostname=`hostname`
export MYhostname
jobnum=$1
jdir=$2
lenv=$3
if test -z "$jobnum"; then
	echo "$0: need job id as first argument and work dir as second"
	exit 1
fi
if test -z "$jdir"; then
	echo "$0: need job ldms data directory as second argument"
	exit 1
fi
if test -z "$lenv"; then
	lenv=$HOME/.ldmsslurmenv.sh
fi
if ! test -f $lenv; then
	echo "$0: need $HOME/.ldmsslurmenv.sh installed or specified as 3rd arg"
	exit 1
fi
. $lenv
# whack agg/store on node 0
if test "0" = "$SLURM_NODEID"; then
	pkill -SIGTERM ldms-aggd
	echo "ldms-aggd killed on $MYhostname"
fi
# whack collector
pid=`cat $LDMSD_PIDFILE`
kill -SIGTERM $pid
ps guxww |grep ldmsd |grep -v grep
ps guxww |grep ldms-aggd |grep -v grep
echo "ldmsd killed on $MYhostname"


exit 0
